- name: Chatbox
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create chatbox user
      become: true
      ansible.builtin.user:
        name: chatbox
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u chatbox
      register: chatbox_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g chatbox
      register: chatbox_gid
      changed_when: false

    - name: Create chatbox k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: chatbox
        namespace: chatbox
        state: present

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: chatbox

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install chatbox helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "chatbox"
        namespace: "chatbox"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"

    - name: Create uptime-push cronjob
      become: true
      ansible.builtin.cron:
        name: "chatbox uptime-push"
        user: "uptimepush"
        minute: "*"
        job: '/usr/local/bin/uptime-push "https://{{ domain }}/" "chatbox" "{{ uptime_endpoint }}"'
