- name: LocalAI
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create localai user
      become: true
      ansible.builtin.user:
        name: localai
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Add user to video group
      become: true
      ansible.builtin.user:
        name: localai
        groups: video
        append: true

    - name: Get gid of video group
      ansible.builtin.shell: "set -o pipefail | getent group video | cut -d: -f3"
      register: video_gid
      changed_when: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u localai
      register: localai_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g localai
      register: localai_gid
      changed_when: false

    - name: Create localai k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: localai
        namespace: localai
        state: present

    - name: Create localai directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/localai"
        state: directory
        owner: localai
        group: localai
        mode: "0700"

    - name: Create localai/localai directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/localai/localai"
        state: directory
        owner: localai
        group: localai
        mode: "0700"

    - name: Create localai/litellm directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/localai/litellm"
        state: directory
        owner: localai
        group: localai
        mode: "0700"

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: localai

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install localai helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "localai"
        namespace: "localai"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"

    - name: Create uptime-push cronjob
      become: true
      ansible.builtin.cron:
        name: "localai uptime-push"
        user: "uptimepush"
        minute: "*"
        job: '/usr/local/bin/uptime-push "https://{{ domain }}/test" "test" "{{ uptime_endpoint }}"'
