---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}
        command: ["/config/entrypoint.sh"]
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}
        volumeMounts:
        - mountPath: /config
          name: data
        - mountPath: /usr/bin/beets-import
          name: data
          subPath: beets-import
        - mountPath: /usr/bin/beets-import-auto
          name: data
          subPath: beets-import-auto
        - mountPath: /usr/bin/tidal-dl
          name: data
          subPath: tidal
        - mountPath: /usr/bin/download-import
          name: data
          subPath: download-import
        - mountPath: /music
          name: music
        - mountPath: /downloads
          name: downloads
        {{- with .Values.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
         claimName: {{ .Values.name }}-data
      - name: music
        persistentVolumeClaim:
         claimName: {{ .Values.name }}-music
      - name: downloads
        persistentVolumeClaim:
         claimName: {{ .Values.name }}-downloads

