- name: RSS Bridge
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create rssbridge user
      become: true
      ansible.builtin.user:
        name: rssbridge
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u rssbridge
      register: rssbridge_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g rssbridge
      register: rssbridge_gid
      changed_when: false

    - name: Create rssbridge k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: rssbridge
        namespace: rssbridge
        state: present

    - name: Create rssbridge app data directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/rssbridge"
        state: directory
        owner: rssbridge
        group: rssbridge
        mode: "0700"

    - name: Ensure directories exist
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/rssbridge/{{ item.path | dirname }}"
        state: directory
        owner: rssbridge
        group: rssbridge
        mode: "0700"
      loop: "{{ lookup('community.general.filetree', 'templates', use_regex=True) }}"
      when: item.state == 'file'

    - name: Apply templates recursively
      become: true
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ kube_app_data }}/rssbridge/{{ item.path }}"
        owner: rssbridge
        group: rssbridge
        mode: "preserve"
      loop: "{{ lookup('community.general.filetree', 'templates', use_regex=True) }}"
      when: item.state == 'file'

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: rssbridge

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install rssbridge helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "rssbridge"
        namespace: "rssbridge"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"

    - name: Create uptime-push cronjob
      become: true
      ansible.builtin.cron:
        name: "rssbridge uptime-push"
        user: "uptimepush"
        minute: "*"
        job: '/usr/local/bin/uptime-push "https://{{ domain }}/" "RSS-Bridge" "{{ uptime_endpoint }}"'
