- name: Install the system-upgrade-controller
  become: false
  kubernetes.core.k8s:
    state: present
    wait: true
    src: https://github.com/rancher/system-upgrade-controller/releases/download/{{ system_upgrade_controller_version }}/system-upgrade-controller.yaml

- name: Label node with k3s-upgrade
  become: false
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ ansible_hostname }}"
        labels:
          k3s-upgrade: 'true'

- name: Configure upgrade plan
  become: false
  kubernetes.core.k8s:
    state: present
    wait: true
    template: templates/upgrade-plan.yaml.j2
