name: wallabag
namespace: wallabag
app:
  image:
    repository: docker.io/wallabag/wallabag
    tag: 2.6.8
postgres:
  image:
    repository: postgres
    tag: 16.1-alpine3.18

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ wallabag_uid.stdout }}
  runAsGroup: {{ wallabag_gid.stdout }}
  fsGroup: {{ wallabag_gid.stdout }}

network:
  php_fpm_port: 9000
  nginx_port: 8080
  ip_whitelist: "{{ ip_whitelist }}"

storage:
  node_name: "{{ ansible_hostname }}"
  data_path: "{{ kube_app_data }}/wallabag"

secrets:
  app:
    WALLABAG_SECRET: "{{ wallabag_secret }}"
    WALLABAG_MAILER_DSN: "{{ wallabag_mailer_dsn }}"
    POSTGRES_PASSWORD: "{{ postgres_password }}"
    PGPASSWORD: "{{ postgres_password }}"
  postgres:
    POSTGRES_PASSWORD: "{{ postgres_password }}"

env:
  domain: "{{ domain }}"
  postgres:
    POSTGRES_DB: "{{ postgres_db }}"
    POSTGRES_USER: "{{ postgres_user }}"
  app:
    DOMAIN_NAME: "https://{{ domain }}"
    WALLABAG_FROM_EMAIL: "{{ wallabag_from_email }}"
    SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
    SYMFONY__ENV__DATABASE_HOST: wallabag-postgres
    SYMFONY__ENV__DATABASE_PORT: 5432
    SYMFONY__ENV__DATABASE_NAME: "{{ postgres_db }}"
    POSTGRES_USER: "{{ postgres_user }}"
