- name: 2.1.1 Ensure time synchronization is in use
  block:
    - name: 2.1.3 Ensure systemd-timesyncd is configured | install systemd-timesyncd
      ansible.builtin.apt:
        name: systemd-timesyncd
        state: present
    - name: 2.1.1.2 Ensure systemd-timesyncd is configured | Configure systemd-timesyncd
      ansible.builtin.template:
        src: templates/timesyncd.conf.j2
        dest: /etc/systemd/timesyncd.conf
        mode: "0644"
        owner: root
        group: root
      notify: Reload timesyncd
    - name: 2.1.3 Ensure systemd-timesyncd is configured | Start and enable systemd-timesyncd
      ansible.builtin.service:
        name: systemd-timesyncd.service
        enabled: true
        state: started
