- name: Add prometheus-community repo
  become: false
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Create monitoring namespace
  become: false
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: monitoring
    namespace: monitoring
    state: present
    wait: true

- name: Install prometheus
  become: false
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "{{ prometheus_stack_version }}"
    release_namespace: monitoring
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait: true
