---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.name }}-zigbee2mqtt
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-zigbee2mqtt
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-zigbee2mqtt
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.zigbee2mqtt.repository }}:{{ .Values.image.zigbee2mqtt.tag }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-zigbee2mqtt
        ports:
        - containerPort: {{ .Values.network.zigbee2mqtt_port }}
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.network.zigbee2mqtt_port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.network.zigbee2mqtt_port }}
        volumeMounts:
          - name: data
            mountPath: /data
            subPath: zigbee2mqtt
        {{- with .Values.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
         claimName: {{ .Values.name }}
