- name: Audiobookshelf
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create audiobookshelf user
      become: true
      ansible.builtin.user:
        name: audiobookshelf
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u audiobookshelf
      register: audiobookshelf_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g audiobookshelf
      register: audiobookshelf_gid
      changed_when: false

    - name: Create audiobookshelf k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: audiobookshelf
        namespace: audiobookshelf
        state: present

    - name: Create audiobookshelf app data directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/audiobookshelf"
        state: directory
        owner: audiobookshelf
        group: audiobookshelf
        mode: "0700"

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: audiobookshelf

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install audiobookshelf helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "audiobookshelf"
        namespace: "audiobookshelf"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"

    - name: Create uptime-push cronjob
      become: true
      ansible.builtin.cron:
        name: "audiobookshelf uptime-push"
        user: "uptimepush"
        minute: "*"
        job: '/usr/local/bin/uptime-push "https://{{ domain }}/" "Audiobookshelf" "{{ uptime_endpoint }}"'
