- name: Download k3s binary
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/latest/download/k3s
    checksum: sha256:https://github.com/k3s-io/k3s/releases/latest/download/sha256sum-amd64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"
