---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  ND_SCANSCHEDULE: "{{ .Values.env.nd_scanschedule }}"
  ND_LOGLEVEL: "{{ .Values.env.nd_loglevel }}"
  ND_SESSIONTIMEOUT: "{{ .Values.env.nd_sessiontimeout }}"
