---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  SMTP_USERNAME: {{ .Values.env.smtp_username | b64enc }}
  SMTP_PASSWORD: {{ .Values.env.smtp_password | b64enc }}
  ADMIN_TOKEN: {{ .Values.env.admin_token | b64enc }}
