name: mistral
context_size: 8192
f16: true
mmap: true
gpu_layers: 33
threads: 5
parameters:
  model: dolphin-2.6-mistral-7b-dpo.Q5_K_M.gguf
  temperature: 0.2
  top_k: 40
  top_p: 0.95
template:
  chat_message: mistral-chat
  chat: mistral-block
  completion: mistral-completion
stopwords:
- <|im_end|>
