name: mixtral
context_size: 4096
f16: true
mmap: true
gpu_layers: 6
threads: 5
low_vram: true
parameters:
  model: dolphin-2.7-mixtral-8x7b.Q5_0.gguf
  temperature: 0.2
  top_k: 40
  top_p: 0.95
  frequency_penalty: 1.1
  batch: 512
  tfz: 1.0
template:
  chat_message: mixtral-chat
  chat: mixtral-block
  completion: mixtral-completion
stopwords:
- <|im_end|>
