name: audiobookshelf
namespace: audiobookshelf
image:
  repository: ghcr.io/advplyr/audiobookshelf
  tag: 2.7.0

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ audiobookshelf_uid.stdout }}
  runAsGroup: {{ audiobookshelf_gid.stdout }}
  fsGroup: {{ audiobookshelf_gid.stdout }}

network:
  service_port_http: 13378
  ip_whitelist: "{{ ip_whitelist }}"

storage:
  node_name: "{{ ansible_hostname }}"
  data_path: "{{ kube_app_data }}/audiobookshelf"
  audiobooks_path: "{{ audiobooks_path }}"
  podcasts_path: "{{ podcasts_path }}"

env:
  domain: "{{ domain }}"
