- name: Allow Kubernetes in UFW
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ item.from_ip }}"
    to_ip: "{{ item.to_ip }}"
    direction: "{{ item.direction }}"
  loop:
    - { rule: "allow", port: "6443", proto: "tcp", from_ip: "any", to_ip: "any", direction: "in" }
    - { rule: "allow", port: "", proto: "any", from_ip: "10.42.0.0/16", to_ip: "any", direction: "in" }
    - { rule: "allow", port: "", proto: "any", from_ip: "10.43.0.0/16", to_ip: "any", direction: "in" }

