- name: YTDL
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create ytdl user
      become: true
      ansible.builtin.user:
        name: ytdl
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u ytdl
      register: ytdl_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g ytdl
      register: ytdl_gid
      changed_when: false

    - name: Create ytdl k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: ytdl
        namespace: ytdl
        state: present

    - name: Create ytdl downloads directory
      become: true
      ansible.builtin.file:
        path: "{{ downloads_path }}"
        state: directory
        owner: ytdl
        group: ytdl
        mode: "0750"

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: ytdl

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install ytdl helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "ytdl"
        namespace: "ytdl"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"
