---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.name }}-localai
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-localai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-localai
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-localai
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.name }}-localai
        image: {{ .Values.localai.image.repository }}:{{ .Values.localai.image.tag }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-localai
        ports:
        - containerPort: {{ .Values.network.localai.http_port }}
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.network.localai.http_port }}
        readinessProbe:
          httpGet:
            path: /v1/models
            port: {{ .Values.network.localai.http_port }}
        volumeMounts:
        - name: data
          subPath: localai
          mountPath: /models
        {{- range $path, $_ := .Files.Glob "files/localai/*" }}
        - name: config
          mountPath: "/models/{{ $path | base }}"
          subPath: {{ $path | base }}
          readOnly: true
        {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
         claimName: {{ .Values.name }}
      - name: config
        configMap:
          name: {{ .Values.name }}-localai-config
