---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-litellm
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-litellm
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.litellm }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
