---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-localai
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-localai
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.network.localai.http_port }}
    targetPort: {{ .Values.network.localai.http_port }}
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-localai
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-litellm
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-litellm
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.network.litellm.http_port }}
    targetPort: {{ .Values.network.litellm.http_port }}
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-litellm
