name: vaultwarden
namespace: vaultwarden
image:
  repository: vaultwarden/server
  tag: 1.30.1-alpine

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ vaultwarden_uid.stdout }}
  runAsGroup: {{ vaultwarden_gid.stdout }}
  fsGroup: {{ vaultwarden_gid.stdout }}

network:
  service_port_http: 8000
  service_port_websocket: 8001

storage:
  node_name: "{{ ansible_hostname }}"
  path: "{{ kube_app_data }}/vaultwarden"

env:
  websocket_enabled: "true"
  signups_allowed: "false"
  domain: "{{ domain }}"
  smtp_host: "{{ smtp_host }}"
  smtp_from: "{{ smtp_from }}"
  smtp_port: "{{ smtp_port }}"
  smtp_ssl: "true"
  smtp_security: "force_tls"
  smtp_username: "{{ smtp_username }}"
  smtp_password: "{{ smtp_password }}"
  admin_token: "{{ admin_token }}"
