- name: Actual
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create actual user
      become: true
      ansible.builtin.user:
        name: actual
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u actual
      register: actual_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g actual
      register: actual_gid
      changed_when: false

    - name: Create actual k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: actual
        namespace: actual
        state: present

    - name: Create actual directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/actual"
        state: directory
        owner: actual
        group: actual
        mode: "0700"

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: actual

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install actual helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "actual"
        namespace: "actual"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"

    - name: Create uptime-push cronjob
      become: true
      ansible.builtin.cron:
        name: "actual uptime-push"
        user: "uptimepush"
        minute: "*"
        job: '/usr/local/bin/uptime-push "https://{{ domain }}/" "Actual" "{{ uptime_endpoint }}"'
