- name: Photoprism
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create photoprism user
      become: true
      ansible.builtin.user:
        name: photoprism
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u photoprism
      register: photoprism_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g photoprism
      register: photoprism_gid
      changed_when: false

    - name: Create photoprism k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: photoprism
        namespace: photoprism
        state: present

    - name: Create photoprism data directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/photoprism"
        state: directory
        owner: photoprism
        group: photoprism
        mode: "0700"

    - name: Create photoprism db data directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/photoprism/db"
        state: directory
        owner: photoprism
        group: photoprism
        mode: "0700"

    - name: Create photoprism app data directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/photoprism/app"
        state: directory
        owner: photoprism
        group: photoprism
        mode: "0700"

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: photoprism

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install photoprism helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "photoprism"
        namespace: "photoprism"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"

    - name: Create uptime-push cronjob
      become: true
      ansible.builtin.cron:
        name: "photoprism uptime-push"
        user: "uptimepush"
        minute: "*"
        job: '/usr/local/bin/uptime-push "https://{{ domain }}/" "PhotoPrism" "{{ uptime_endpoint }}"'
