name: rssbridge
namespace: rssbridge
image:
  repository: docker.io/rssbridge/rss-bridge
  tag: "2023-09-24"

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ rssbridge_uid.stdout }}
  runAsGroup: {{ rssbridge_gid.stdout }}
  fsGroup: {{ rssbridge_gid.stdout }}

network:
  service_port_http: 8080
  ip_whitelist: "{{ ip_whitelist }}"

storage:
  node_name: "{{ ansible_hostname }}"
  data_path: "{{ kube_app_data }}/rssbridge"

secrets:
  DENNIKN_AUTH_COOKIE: {{ dennikn_auth_cookie }}

env:
  domain: "{{ domain }}"
