---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-app
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.network.nginx_port }}
    targetPort: {{ .Values.network.nginx_port }}
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-postgres
spec:
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-postgres
