name: invidious
namespace: invidious
app:
  image:
    repository: quay.io/invidious/invidious
    tag: bb14f794969f62582917a39c2dd57bf92fa146a7
postgres:
  image:
    repository: postgres
    tag: 16.1-alpine3.18

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ invidious_uid.stdout }}
  runAsGroup: {{ invidious_gid.stdout }}
  fsGroup: {{ invidious_gid.stdout }}

network:
  service_port_http: 3000
  ip_whitelist: "{{ ip_whitelist }}"

storage:
  node_name: "{{ ansible_hostname }}"
  db_path: "{{ kube_app_data }}/invidious"

secrets:
  postgres:
    POSTGRES_PASSWORD: "{{ postgres_password }}"

env:
  domain: "{{ domain }}"
  postgres:
    POSTGRES_DB: "{{ postgres_db }}"
    POSTGRES_USER: "{{ postgres_user }}"
  app:
    INVIDIOUS_CONFIG: |
      db:
        dbname: "invidious"
        user: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        host: invidious-postgres
        port: 5432
      external_port: 443
      domain: {{ domain }}
      https_only: true
      check_tables: true
      playlist_length_limit: 99999
      hmac_key: "{{ invidious_hmac_key }}"
