---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-app
data:
  {{- range $key, $val := .Values.env.app }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-postgres
data:
  {{- range $key, $val := .Values.env.postgres }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-runner
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-runner
data:
  {{- range $key, $val := .Values.env.runner }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-runner-files
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-runner-files
data:
  subuid: |
    dockremap:1000000:1000000
    rootless:10000000:1000000
  subgid: |
    dockremap:1000000:1000000
    rootless:10000000:1000000
