---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-app
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-app
        - secretRef:
            name: {{ .Values.name }}-app
        ports:
        - containerPort: {{ .Values.network.service_port_http }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.network.service_port_ssh }}
          name: ssh
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.network.service_port_http }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.network.service_port_http }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/gitea
          subPath: gitea-lib
        - name: data
          mountPath: /etc/gitea
          subPath: gitea-etc
        {{- with .Values.resources.app }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
         claimName: {{ .Values.name }}
