- name: Gitea
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create gitea user
      become: true
      ansible.builtin.user:
        name: gitea
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u gitea
      register: gitea_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g gitea
      register: gitea_gid
      changed_when: false

    - name: Create gitea k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: gitea
        namespace: gitea
        state: present

    - name: Create gitea directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/gitea"
        state: directory
        owner: gitea
        group: gitea
        mode: "0700"

    - name: Create gitea-etc directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/gitea/gitea-etc"
        state: directory
        owner: gitea
        group: gitea
        mode: "0700"

    - name: Create gitea-lib directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/gitea/gitea-lib"
        state: directory
        owner: gitea
        group: gitea
        mode: "0700"

    - name: Create gitea runner directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/gitea/gitea-runner"
        state: directory
        owner: 1000
        group: 1001
        mode: "0700"

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: gitea

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install gitea helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "gitea"
        namespace: "gitea"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"

    - name: Create uptime-push cronjob
      become: true
      ansible.builtin.cron:
        name: "gitea uptime-push"
        user: "uptimepush"
        minute: "*"
        job: '/usr/local/bin/uptime-push "https://{{ domain }}/" "Gitea" "{{ uptime_endpoint }}"'
