name: jellyfin
namespace: jellyfin
image:
  repository: docker.io/jellyfin/jellyfin
  tag: 10.8.11

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ jellyfin_uid.stdout }}
  runAsGroup: {{ jellyfin_gid.stdout }}
  fsGroup: {{ jellyfin_gid.stdout }}
  supplementalGroups: [{{ytdl_gid.stdout }}]

network:
  service_port_http: 8003

storage:
  node_name: "{{ ansible_hostname }}"
  data_path: "{{ kube_app_data }}/jellyfin"
  media_path: "{{ media_path }}"
  youtube_path: "{{ youtube_path }}"

env:
  domain: "{{ domain }}"
