---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.network.calibre_port_http }}
          name: calibre
          protocol: TCP
        - containerPort: {{ .Values.network.calibre_web_port_http }}
          name: web
          protocol: TCP
        livenessProbe:
          httpGet:
            port: {{ .Values.network.calibre_port_http }}
        readinessProbe:
          httpGet:
            port: {{ .Values.network.calibre_port_http }}
        volumeMounts:
        - mountPath: /config
          name: data
        - mountPath: /etc/s6-overlay/s6-rc.d/init-kasmvnc-config/run
          name: data
          subPath: override/init-kasmvnc-config
        - mountPath: /books
          name: books
        {{- with .Values.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
         claimName: {{ .Values.name }}
      - name: books
        persistentVolumeClaim:
         claimName: {{ .Values.name }}-books
