---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  users: {{ .Values.secrets.calibre_auth | b64enc | quote}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-web-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  users: {{ .Values.secrets.calibre_web_auth | b64enc | quote}}
