---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1000P # size of local volume is only limited by the size of the node
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.storage.data_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.node_name }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-books
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1000P # size of local volume is only limited by the size of the node
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.storage.books_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.node_name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000P
  storageClassName: "local-storage"
  volumeName: {{ .Values.name }}-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-books
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000P
  storageClassName: "local-storage"
  volumeName: {{ .Values.name }}-books
