name: localai
namespace: localai
image:
  repository: quay.io/go-skynet/local-ai
  tag: v1.40.0

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ localai_uid.stdout }}
  runAsGroup: {{ localai_gid.stdout }}
  fsGroup: {{ localai_gid.stdout }}

network:
  http_port: 8080
  ip_whitelist: "{{ ip_whitelist }}"

storage:
  node_name: "{{ ansible_hostname }}"
  data_path: "{{ kube_app_data }}/localai"

env:
  domain: "{{ domain }}"
  THREADS: 6
  MODELS_PATH: /models
  DEBUG: "false"
  SINGLE_ACTIVE_BACKEND: "false"


