name: localai
namespace: localai
localai:
  image:
    repository: quay.io/go-skynet/local-ai
    tag: sha-2f7beb6-cublas-cuda11-core
litellm:
  image:
    repository: ghcr.io/berriai/litellm
    tag: main-v1.12.3

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ localai_uid.stdout }}
  runAsGroup: {{ localai_gid.stdout }}
  fsGroup: {{ localai_gid.stdout }}

network:
  localai:
    http_port: 8080
  litellm:
    http_port: 8000

storage:
  node_name: "{{ ansible_hostname }}"
  data_path: "{{ kube_app_data }}/localai"

secrets:
  litellm:
    OPENAI_API_KEY: "{{ openai_api_key }}"
    LOCALAI_API_KEY: "{{ localai_api_key }}"

env:
  domain: "{{ domain }}"
  localai:
    THREADS: 6
    MODELS_PATH: /models
    DEBUG: "true"
    SINGLE_ACTIVE_BACKEND: "true"
  litellm:
    PIP_CACHE_DIR: /tmp/pip
    PYTHONUSERBASE: /tmp/pythonuserbase
