name: nextcloud
namespace: nextcloud
app:
  image:
    repository: docker.io/nextcloud
    tag: 27.1.3-apache
redis:
  image:
    repository: docker.io/redis
    tag: 7.2.3-alpine3.18
mariadb:
  image:
    repository: docker.io/mariadb
    tag: 11.2.2

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ nextcloud_uid.stdout }}
  runAsGroup: {{ nextcloud_gid.stdout }}
  fsGroup: {{ nextcloud_gid.stdout }}

network:
  service_port_http: {{ service_port_http }}
  ip_whitelist: "{{ ip_whitelist }}"

storage:
  node_name: "{{ ansible_hostname }}"
  app_path: "{{ kube_app_data }}/nextcloud"
  data_path: "{{ data_path }}"

secrets:
  mariadb:
    MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    MYSQL_PASSWORD: "{{ mysql_password }}"
  app:
    MYSQL_PASSWORD: "{{ mysql_password }}"

env:
  domain: "{{ domain }}"
  mariadb:
    MYSQL_DATABASE: "{{ mysql_database }}"
    MYSQL_USER: "{{ mysql_user }}"
  app:
    DOMAIN: "{{ domain }}"
    MYSQL_HOST: "nextcloud-mariadb"
    REDIS_HOST: "nextcloud-redis"
    MYSQL_DATABASE: "{{ mysql_database }}"
    MYSQL_USER: "{{ mysql_user }}"
    PHP_MEMORY_LIMIT: "2048M"
