- name: Beets
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create beets user
      become: true
      ansible.builtin.user:
        name: beets
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u beets
      register: beets_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g beets
      register: beets_gid
      changed_when: false

    - name: Create beets k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: beets
        namespace: beets
        state: present

    - name: Create beets app data directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/beets"
        state: directory
        owner: beets
        group: beets
        mode: "0700"

    - name: Create beets downloads directory
      become: true
      ansible.builtin.file:
        path: "{{ downloads_path }}"
        state: directory
        owner: beets
        group: beets
        mode: "0700"

    - name: Apply templates recursively
      become: true
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ kube_app_data }}/beets/{{ item.path }}"
        owner: beets
        group: beets
        mode: "preserve"
      loop: "{{ lookup('community.general.filetree', 'templates', use_regex=True, wantlist=True) }}"
      when: item.state == 'file'

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: beets

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install beets helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "beets"
        namespace: "beets"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"
