name: navidrome
namespace: navidrome
image:
  repository: deluan/navidrome
  tag: 0.50.0

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: {{ navidrome_uid.stdout }}
  runAsGroup: {{ navidrome_gid.stdout }}
  fsGroup: {{ navidrome_gid.stdout }}

network:
  service_port_http: 8002
  ip_whitelist: "{{ ip_whitelist }}"

storage:
  node_name: "{{ ansible_hostname }}"
  data_path: "{{ kube_app_data }}/navidrome"
  music_path: "{{ music_path }}"

env:
  domain: "{{ domain }}"
  nd_scanschedule: "{{ nd_scanschedule }}"
  nd_loglevel: "{{ nd_loglevel }}"
  nd_sessiontimeout: "{{ nd_sessiontimeout }}"
