---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.name }}-brscan
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-brscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-brscan
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-brscan
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.brscan.image.repository }}:{{ .Values.brscan.image.tag }}
        imagePullPolicy: Always
        name: {{ .Values.name }}-brscan
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-brscan
        ports:
        - name: brscan
          protocol: UDP
          containerPort: {{ .Values.network.brscan_port }}
        volumeMounts:
        - name: data
          mountPath: /output
          subPath: app/consume
        - name: data
          mountPath: /brother-scan.yaml
          subPath: brscan/brother-scan.yaml
        - name: data
          mountPath: /etc/opt/brother/scanner/brscan4/brsanenetdevice4.cfg
          subPath: brscan/brsanenetdevice4.cfg
      volumes:
      - name: data
        persistentVolumeClaim:
         claimName: {{ .Values.name }}
