---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-app
data:
  {{- range $key, $val := .Values.env.app }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-postgres
data:
  {{- range $key, $val := .Values.env.postgres }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
