---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.env.domain }}`) && PathPrefix(`/`)
    services:
    - name: {{ .Values.name }}-app
      port: {{ .Values.network.service_port_http }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Values.name }}-brscan
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - brscan
  routes:
  - services:
    - name: {{ .Values.name }}-brscan
      port: {{ .Values.network.brscan_port }}
