---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.name }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-redis
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}-redis
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
        {{- with .Values.resources.redis }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: redis
      volumes:
      - name: data
        persistentVolumeClaim:
         claimName: {{ .Values.name }}
