---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-app
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.app }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-postgres
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.postgres }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
