---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-app
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.network.service_port_http }}
    targetPort: {{ .Values.network.service_port_http }}
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-postgres
spec:
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-redis
spec:
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-brscan
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-brscan
spec:
  ports:
  - name: brscan
    protocol: UDP
    port: {{ .Values.network.brscan_port }}
    targetPort: {{ .Values.network.brscan_port }}
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-brscan
