---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}
        ports:
        - containerPort: 13378
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
        - name: data
          mountPath: /config
          subPath: config
        - name: data
          mountPath: /metadata
          subPath: metadata
        - name: audiobooks
          mountPath: /audiobooks
        - name: podcasts
          mountPath: /podcasts
        {{- with .Values.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
         claimName: {{ .Values.name }}-data
      - name: audiobooks
        persistentVolumeClaim:
         claimName: {{ .Values.name }}-audiobooks
      - name: podcasts
        persistentVolumeClaim:
         claimName: {{ .Values.name }}-podcasts
