---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-data
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1000P # size of local volume is only limited by the size of the node
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.storage.data_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.node_name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-audiobooks
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1000P # size of local volume is only limited by the size of the node
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.storage.audiobooks_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.node_name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-podcasts
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1000P # size of local volume is only limited by the size of the node
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.storage.podcasts_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.node_name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000P
  storageClassName: "local-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-audiobooks
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000P
  storageClassName: "local-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-podcasts
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000P
  storageClassName: "local-storage"
