- name: Copy Traefik config
  ansible.builtin.template:
    src: "files/traefik-config.yaml"
    dest: "{{ k3s_server_location }}/server/manifests/traefik-config.yaml"
    owner: root
    group: root
    mode: "0600"

- name: Apply Traefik config
  ansible.builtin.command: >-
    kubectl apply -f "{{ k3s_server_location }}/server/manifests/traefik-config.yaml"
  changed_when: true

- name: Update sources
  ansible.builtin.apt:
    update_cache: true

- name: Install Pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Install required Python libraries
  become: false
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "--user --break-system-packages"
  loop:
    - helm
    - PyYAML
    - kubernetes
    - jsonpatch

- name: Install helm
  become: true
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  args:
    creates: /usr/local/bin/helm

- name: Install Helm diff plugin
  become: false
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present

- name: Install the system-upgrade-controller
  become: false
  kubernetes.core.k8s:
    state: present
    src: https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml

- name: Label node with k3s-upgrade
  become: false
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ ansible_hostname }}"
        labels:
          k3s-upgrade: 'true'

- name: Configure upgrade plan
  become: false
  kubernetes.core.k8s:
    state: present
    template: files/upgrade-plan.yaml

- name: Install kill-k3s script
  ansible.builtin.template:
    src: "templates/kill-k3s.j2"
    dest: /usr/local/bin/kill-k3s
    owner: root
    group: root
    mode: "0755"
