- name: Update sources
  ansible.builtin.apt:
    update_cache: true

- name: Install Pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Install required Python libraries
  become: false
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "--user --break-system-packages"
  loop:
    - helm
    - PyYAML
    - kubernetes
    - jsonpatch

- name: Install helm
  become: true
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  args:
    creates: /usr/local/bin/helm

- name: Install Helm diff plugin
  become: false
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present

- name: Install kill-k3s script
  ansible.builtin.template:
    src: "templates/kill-k3s.j2"
    dest: /usr/local/bin/kill-k3s
    owner: root
    group: root
    mode: "0755"

- name: Increase inotify limits
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "fs.inotify.max_user_watches", value: "2099999999" }
    - { key: "fs.inotify.max_user_instances", value: "2099999999" }
    - { key: "fs.inotify.max_queued_events", value: "2099999999" }
