- name: Wallabag
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create wallabag user
      become: true
      ansible.builtin.user:
        name: wallabag
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u wallabag
      register: wallabag_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g wallabag
      register: wallabag_gid
      changed_when: false

    - name: Create wallabag k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: wallabag
        namespace: wallabag
        state: present

    - name: Create wallabag directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/wallabag"
        state: directory
        owner: wallabag
        group: wallabag
        mode: "0700"

    - name: Create wallabag postgres directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/wallabag/postgres"
        state: directory
        owner: wallabag
        group: wallabag
        mode: "0700"

    - name: Create wallabag app directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/wallabag/app"
        state: directory
        owner: wallabag
        group: wallabag
        mode: "0700"

    - name: Create wallabag app var directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/wallabag/app/var"
        state: directory
        owner: wallabag
        group: wallabag
        mode: "0700"

    - name: Create entrypoint.sh from template
      become: true
      ansible.builtin.template:
        src: templates/entrypoint.sh
        dest: "{{ kube_app_data }}/wallabag/app/var/entrypoint.sh"
        mode: "0700"
        owner: wallabag
        group: wallabag

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: wallabag

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install wallabag helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "wallabag"
        namespace: "wallabag"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"

    - name: Create uptime-push cronjob
      become: true
      ansible.builtin.cron:
        name: "wallabag uptime-push"
        user: "uptimepush"
        minute: "*"
        job: '/usr/local/bin/uptime-push "https://{{ domain }}/" "wallabag" "{{ uptime_endpoint }}"'
