---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.network.service_port_http }}
    targetPort: {{ .Values.network.service_port_http }}
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
