- name: Paperless
  hosts: server
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Create paperless user
      become: true
      ansible.builtin.user:
        name: paperless
        state: present
        shell: /usr/sbin/nologin
        system: false
        create_home: false

    - name: Get uid and gid of user
      ansible.builtin.command: id -u paperless
      register: paperless_uid
      changed_when: false

    - name: Get gid of user
      ansible.builtin.command: id -g paperless
      register: paperless_gid
      changed_when: false

    - name: Create paperless k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: paperless
        namespace: paperless
        state: present

    - name: Create paperless directory
      become: true
      ansible.builtin.file:
        path: "{{ kube_app_data }}/paperless"
        state: directory
        owner: paperless
        group: paperless
        mode: "0700"

    - name: Create paperless data directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: paperless
        group: paperless
        mode: "0700"
      with_items:
        - "{{ kube_app_data }}/paperless/app"
        - "{{ kube_app_data }}/paperless/postgres"
        - "{{ kube_app_data }}/paperless/redis"

    - name: Create paperless app directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: paperless
        group: paperless
        mode: "0700"
      with_items:
        - "{{ kube_app_data }}/paperless/app/consume"
        - "{{ kube_app_data }}/paperless/app/data"
        - "{{ kube_app_data }}/paperless/app/export"
        - "{{ kube_app_data }}/paperless/app/media"

    - name: Create temporary build directory
      register: build_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: paperless

    - name: Copy helm chart to target
      ansible.builtin.copy:
        src: chart/
        dest: "{{ build_dir.path }}"
        mode: "0700"

    - name: Create values.yaml from template
      ansible.builtin.template:
        src: chart/values.yaml
        dest: "{{ build_dir.path }}/values.yaml"
        mode: "0600"

    - name: Install paperless helm chart
      kubernetes.core.helm:
        chart_ref: "{{ build_dir.path }}"
        name: "paperless"
        namespace: "paperless"
        state: present

    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir.path }}"

    - name: Create uptime-push cronjob
      become: true
      ansible.builtin.cron:
        name: "paperless uptime-push"
        user: "uptimepush"
        minute: "*"
        job: '/usr/local/bin/uptime-push "https://{{ domain }}/" "Paperless-ngx" "{{ uptime_endpoint }}"'
