- name: Copy Traefik config
  ansible.builtin.template:
    src: "files/traefik-config.yaml"
    dest: "{{ k3s_server_location }}/server/manifests/traefik-config.yaml"
    owner: root
    group: root
    mode: "0600"

- name: Apply Traefik config
  ansible.builtin.command: >-
    kubectl apply -f "{{ k3s_server_location }}/server/manifests/traefik-config.yaml"
  changed_when: true

- name: Restart traefik
  ansible.builtin.command: >-
    kubectl rollout restart deployment traefik -n kube-system
  changed_when: true

- name: Cleanup
  ansible.builtin.file:
    state: absent
    path: "/tmp/append.yaml"
