---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-app
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.photoprism }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-mariadb
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-mariadb
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.mariadb }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
