---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-app
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.network.service_port_http }}
    targetPort: {{ .Values.network.service_port_http }}
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-mariadb
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-mariadb
spec:
  ports:
  - name: mariadb
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-mariadb
