---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/buffering: |
      maxrequestbodybytes: 2147483648
    traefik.ingress.kubernetes.io/redirect-permanent: 'true'
    traefik.ingress.kubernetes.io/redirect-regex: https://(.*)/.well-known/(card|cal)dav
    traefik.ingress.kubernetes.io/redirect-replacement: https://$$1/remote.php/dav/
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.env.domain }}`) && PathPrefix(`/`)
    middlewares:
      - name: {{ .Values.name }}-ipwhitelist
        namespace: {{ .Values.namespace }}
      - name: {{ .Values.name }}-auth
        namespace: {{ .Values.namespace }}
    services:
    - name: {{ .Values.name }}-app
      port: {{ .Values.network.service_port_http }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.name }}-ipwhitelist
  namespace: {{ .Values.namespace }}
spec:
  ipWhiteList:
    sourceRange:
    {{- range $ip := splitList "," .Values.network.ip_whitelist }}
      - "{{ $ip }}"
    {{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.name }}-auth
  namespace: {{ .Values.namespace }}
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
    customFrameOptionsValue: "SAMEORIGIN"
