---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-app
    spec:
      serviceAccountName: {{ .Values.name }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}-app
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-app
        - secretRef:
            name: {{ .Values.name }}-app
        livenessProbe:
          httpGet:
            path: /status.php
            port: {{ .Values.network.service_port_http }}
        volumeMounts:
        - name: app
          mountPath: /var/www/html
          subPath: app
        - name: app
          mountPath: /usr/local/etc/php/conf.d/redis-session.ini
          subPath: redis-session.ini
        - name: app
          mountPath: /etc/apache2/ports.conf
          subPath: ports.conf
        - name: data
          mountPath: /var/www/html/data
        {{- with .Values.resources.app }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: app
        persistentVolumeClaim:
         claimName: {{ .Values.name }}-app
      - name: data
        persistentVolumeClaim:
         claimName: {{ .Values.name }}-data
